#!/usr/bin/env python
"""Check the hand-written migration against the models. No database required.

Migration 0001 is hand-written rather than autogenerated, so nothing stops the models
and the migration from drifting apart -- and the failure mode is a container that
starts fine and then errors on the first query. This parses the migration's AST and
compares tables, columns and indexes against ``Base.metadata``.

    python scripts/check_schema_drift.py
"""
from __future__ import annotations

import ast
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from app.domain.models import Base

MIGRATION = (
    pathlib.Path(__file__).resolve().parent.parent
    / "app/db/migrations/versions/0001_initial_schema.py"
)


def parse_migration() -> tuple[dict[str, set[str]], set[str]]:
    """Extract {table: {columns}} and {index names} from the migration source."""
    tree = ast.parse(MIGRATION.read_text(encoding="utf-8"))
    tables: dict[str, set[str]] = {}
    indexes: set[str] = set()

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        fn = getattr(node.func, "attr", None)

        if fn == "create_table" and node.args:
            tables[node.args[0].value] = {
                arg.args[0].value
                for arg in node.args[1:]
                if isinstance(arg, ast.Call) and getattr(arg.func, "attr", "") == "Column"
            }
        elif fn == "create_index" and len(node.args) >= 2:
            indexes.add(node.args[0].value)
        elif fn == "execute" and node.args:
            # Partial indexes are raw SQL, since Alembic's helper cannot express them.
            stmt = node.args[0]
            text = (
                stmt.value
                if isinstance(stmt, ast.Constant)
                else "".join(
                    v.value for v in getattr(stmt, "values", []) if isinstance(v, ast.Constant)
                )
            )
            if "CREATE" in text and "INDEX" in text:
                parts = text.split()
                indexes.add(parts[parts.index("INDEX") + 1])

    return tables, indexes


def main() -> int:
    migration_tables, migration_indexes = parse_migration()
    model_tables = {t.name: {c.name for c in t.columns} for t in Base.metadata.sorted_tables}
    model_indexes = {i.name for t in Base.metadata.sorted_tables for i in t.indexes}

    problems: list[str] = []

    for name, columns in model_tables.items():
        if name not in migration_tables:
            problems.append(f"table {name!r} is in the models but not the migration")
            continue
        if missing := columns - migration_tables[name]:
            problems.append(f"{name}: migration is missing columns {sorted(missing)}")
        if extra := migration_tables[name] - columns:
            problems.append(f"{name}: migration has columns the models lack {sorted(extra)}")

    for name in migration_tables.keys() - model_tables.keys():
        problems.append(f"table {name!r} is in the migration but not the models")

    if missing := model_indexes - migration_indexes:
        problems.append(f"indexes missing from the migration: {sorted(missing)}")
    if extra := migration_indexes - model_indexes:
        problems.append(f"indexes only in the migration: {sorted(extra)}")

    print(f"{len(model_tables)} tables, {len(model_indexes)} indexes checked")
    if problems:
        print("\nSCHEMA DRIFT:")
        for problem in problems:
            print(f"  - {problem}")
        return 1
    print("SCHEMA MATCHES")
    return 0


if __name__ == "__main__":
    sys.exit(main())
